---

- name: Include vars
  include_vars: vars/main.yml


- name: Clone AWX project from officiel github project
  git:
    repo: "{{git_repo_AWX}}"
    dest: "{{dest_repo}}"

- name: Run AWX playbook install 
  shell:  ansible-playbook -i inventory install.yml
  args: 
    chdir:  "{{AWX_installer}}"
  
