---

- name: Include vars
  include_vars: vars/main.yml

- name: create dir to clone AWX repo
  file:
    path: "{{dest_repo}}"
    state: directory
    mode: '0775'

- name: Clone AWX project from officiel github project
  git:
    repo: "{{git_repo_AWX}}"
    dest: "{{dest_repo}}"

- name: Run AWX playbook install 
  shell:  ansible-playbook -i inventory install.yml
  args: 
    chdir:  "{{AWX_installer}}"
  
