---

- name: Include vars
  include_vars: vars/main.yml

- name: Remove all old package
  apt:
    name: docker docker-engine docker.io containerd runc
    state: absent

- name: Update
  apt:
    update-cache: yes

- name: Install package
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add key GPG
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repository
  apt_repository:
    repo: "{{docker_repo}}"
    state: present

- name: Update
  apt:
    update-cache: yes


- name: Install package
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python-pip
    - docker-compose
    - build-essential
    - git
    - nodejs
    - npm


- name: Install pip module
  pip:
    name: 
    - docker
    - docker-compose

- name: Running the container test hello world for test
  docker_container:
     image: hello-world
     name : hello-world_test
